apriltag:
  ros__parameters:
    image_transport: raw
    family: 36h11
    size: 0.15
    max_hamming: 0
    detector:
      threads: 2
      decimate: 2.0
      blur: 0.0
      refine: 1
      sharpening: 0.25
    publish_tf: true
    tag:
      ids: [3]
      frames: [tag_150mm]
      sizes: [0.15]